# Python support can be specified down to the minor or micro version
# (e.g. 3.6 or 3.6.3).
# OS Support also exists for jessie & stretch (slim and full).
# See https://hub.docker.com/r/library/python/ for all supported Python
# tags from Docker Hub.
FROM floydhub/pytorch:1.0.0-py3.40
MAINTAINER zergmk2
LABEL Name=chineseocr Version=0.0.2
EXPOSE 8080

WORKDIR /app
ADD . /app
RUN git submodule init && git submodule update
RUN cd darknet/ && make && cd ..
VOLUME /app/models
RUN pip install -r requirements.txt --no-cache-dir
RUN cd text/detector/utils && sh make-for-cpu.sh && cd ..
CMD ["ipython", "app.py", "8080"]
